version: '3.3'
services:
    adminer:
        ports:
            - 8080
        volumes:
            - ./adminer/entrypoint.sh:/usr/local/bin/entrypoint.sh
        environment:
            - ADMINER_PLUGINS=sql-log dump-json
            #- ADMINER_DESIGN=pappu687
            - ADMINER_DESIGN=https://raw.githubusercontent.com/pepa-linha/Adminer-Design-Dark/master/adminer.css
        image: adminer

    db:
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=demo
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        image: mysql
        command: --default-authentication-plugin=mysql_native_password