version: '3.3'
services:
    adminer:
        ports:
            - 8080
        environment:
            - ADMINER_PLUGINS=sql-log dump-json
        image: adminer

    db:
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=demo
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        image: mysql
        command: --default-authentication-plugin=mysql_native_password