version: '3.3'
services:
    adminer:
        ports:
            - 8080
        image: lalyos/adminer
    db:
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=demo
        image: mysql
        command: --default-authentication-plugin=mysql_native_password